apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - rbac.yaml
  - deployment.yaml

# Optional: Add common labels
commonLabels:
  project: watch-my-pod

# Optional: Add namespace if different
# namespace: watch-my-pod
